### Sign-up

POST http://localhost:3011/api/addUser/
content-type: application/json

{
  "firstName" : "yusri",
  "surname" : "Ahmed",
  "email" : "Laylahqf01@g6mail.com",
  "username" : "Yfqyrrhtfy",
  "password" : "00qyh060",
  "userType" : "admin"
}

### Login

POST http://localhost:3011/api/login/
content-type: application/json

{
  "username" : "youshi",
  "password" : "youshi"
}